export const GET_SCORE = 'GET_SCORE';
export const INCREMENTED_SCORE = 'INCREMENTED_SCORE';
export const SCORE_RESET = 'SCORE_RESET';
export const INCREMENTED_PROGRESS = 'INCREMENTED_PROGRESS';
export const PROGRESS_RESET = 'PROGRESS_RESET';

export const SUBMITTED_RESPONSE_A = 'SUBMITTED_RESPONSE_A';
export const SUBMITTED_RESPONSE_B = 'SUBMITTED_RESPONSE_B';
export const SUBMITTED_RESPONSE_C = 'SUBMITTED_RESPONSE_C';
export const SUBMITTED_RESPONSE_D = 'SUBMITTED_RESPONSE_D';

export const GOT_FEEDBACK_SUCCESS = 'GOT_FEEDBACK_SUCCESS';
export const GOT_FEEDBACK_FAIL = 'GOT_FEEDBACK_FAIL';

export const POSITIVE_CORRECTION_ARRAY_ADD = 'POSITIVE_CORRECTION_ARRAY_ADD';
export const NEGATIVE_CORRECTION_ARRAY_ADD = 'NEGATIVE_CORRECTION_ARRAY_ADD';
