export const GET_SCORE = 'GET_SCORE';
export const INCREMENTED_SCORE = 'INCREMENTED_SCORE';
export const INCREMENTED_PROGRESS = 'INCREMENTED_PROGRESS';

export const GOT_FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const GOT_FEEDBACK_FAIL = 'FEEDBACK_FAIL';

//export const SET_RESPONSE = 'SET_RESPONSE';
export const REQ_CORRECTION_ARRAY = 'REQ_CORRECTION_ARRAY';
